runtime: nodejs14

handlers:
  - url: /assets
    static_dir: public/assets
  - url: /.*
    static_files: public/index.html
    upload: public/index.html

env_variables:
  NODE_ENV: production

entrypoint: node app.js
